# Generated by Django 5.0.7 on 2024-07-26 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_initial"),
        ("user", "0002_alter_user_org_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="org_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_organization",
                to="organization.organization",
            ),
        ),
    ]
